data:
  batch_size: 4
  num_workers: 0
  train_dir: "../datasets/Thyroid_Dataset/tn3k/trainval-image"
  train_ann: "../datasets/Thyroid_Dataset/tn3k/train_annotations.csv"
  val_dir: "../datasets/Thyroid_Dataset/tn3k/test-image"
  val_ann: "../datasets/Thyroid_Dataset/tn3k/test_annotations.csv"
model:
  config_path: groundingdino/config/GroundingDINO_SwinT_OGC.py
  lora_weights: weights/checkpoint_epoch_45.pth
  weights_path: weights/groundingdino_swint_ogc.pth
training:
  learning_rate: 0.0001
  num_epochs: 200
  save_dir: weights
  save_frequency: 5
  use_lora: true
  visualization_frequency: 5
  warmup_epochs: 5
