data:
  train_dir: "../datasets/Thyroid_Dataset/tn3k/trainval-image"
  train_ann: "../datasets/Thyroid_Dataset/tn3k/train_annotations.csv"
  val_dir: "../datasets/Thyroid_Dataset/tn3k/test-image"
  val_ann: "../datasets/Thyroid_Dataset/tn3k/test_annotations.csv"
  batch_size: 10
  num_workers: 0

model:
  config_path: "groundingdino/config/GroundingDINO_SwinT_OGC.py"
  lora_weights: weights/20250105_1818/checkpoint_epoch_45.pth
  weights_path: weights/groundingdino_swint_ogc.pth
training:
  num_epochs: 200
  learning_rate: 5e-5
  save_dir: "weights"
  save_frequency: 5
  warmup_epochs: 5
  use_lora: true
  visualization_frequency: 5